# Generated by Django 4.2.2 on 2023-06-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='size',
        ),
    ]
